# Generated by Django 4.1.13 on 2026-03-30 21:33

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('enrollment_year', models.IntegerField()),
                ('subjects', djongo.models.fields.JSONField(default=list)),
                ('attendance', djongo.models.fields.JSONField(default=dict)),
                ('fees', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'academic_records',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
