# Generated by Django 4.1.13 on 2026-03-30 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicrecord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
